version: '3.7'

services:
  test: 
    container_name: workship_docker_compose_test
    image: node:18-alpine3.15
    command: npm run start:debug
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 81:80
    volumes:
      - .:/usr/src/app

  elastic:
    container_name: elastic_search
    image: elasticsearch:8.4.3
    ports:
      - 9201:9200
      