version: '3.7'

services:
    dev:
        container_name: workshop_docker_compose_dev
        image: node:18-alpine3.15
        command: npm run start:debug
        ports:
            - 8030:8030
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - .:/usr/src/app
            - /usr/src/app/node_modules